// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID          string           `json:"id"`
	CustomerID  string           `json:"customer_id"`
	ProductID   string           `json:"product_id"`
	Price       pgtype.Numeric   `json:"price"`
	Quantity    int32            `json:"quantity"`
	OrderStatus *string          `json:"order_status"`
	OrderDATE   pgtype.Timestamp `json:"order_DATE"`
}

type Product struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Price     pgtype.Numeric   `json:"price"`
	Stock     int32            `json:"stock"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
