// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID         string           `json:"id"`
	CustomerID *string          `json:"customer_id"`
	ProductID  *string          `json:"product_id"`
	Quantity   string           `json:"quantity"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Stock     string           `json:"stock"`
	Price     string           `json:"price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
