// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) ([]Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) ([]Product, error)
	DeleteCustomer(ctx context.Context, id string) error
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetCustomerByID(ctx context.Context, id string) (Customer, error)
	GetOrderById(ctx context.Context, id string) (Order, error)
	GetProductById(ctx context.Context, id string) ([]GetProductByIdRow, error)
	UpdateByIdProduct(ctx context.Context, arg UpdateByIdProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
