# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v2.1  

  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.23.8'
          go-package: './...'

  build:
    runs-on: ubuntu-latest
    needs: [test, govulncheck_job]  # Ensure this job runs only after lint and vulnerability check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...