# This workflow automates CI for the PostgreSQL project
# It scans for vulnerabilities, lints the code, runs tests, and builds the Go binary.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49.0  

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.22
          go-package: ./...
      # Ensure modules are tidy and all dependencies are downloaded
      - name: Download Go Modules
        run: |
          go mod tidy
          go mod download

      # Now run the vulnerability check
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -C . -format text ./...

  test:
    runs-on: ubuntu-latest
    needs: [golangci, govulncheck]  # Ensure tests run only after linting and vulnerability check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: [test]  # Only build after tests have passed
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...
